name: Build, Test, and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # Modifier selon votre version du SDK
      
      - name: Remplacer les variables dans NuGet.config
        run: |
           sed -i "s|{NUGET_USERNAME}|${{ secrets.NUGET_USERNAME }}|g" src/nuget.config
           sed -i "s|{NUGET_PASSWORD}|${{ secrets.NUGET_PASSWORD }}|g" src/nuget.config
      
      - name: Restore dependencies
        run: dotnet restore src/BitCrafts.Module.Users.sln

      - name: Build project
        run: dotnet build src/BitCrafts.Module.Users.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test src/BitCrafts.Module.Users.sln --no-restore --verbosity normal

      - name: Pack NuGet package
        run: dotnet pack src/BitCrafts.Module.Users.sln --configuration Release --no-restore --output .

      - name: Publish NuGet package to GitHub Packages
        run: dotnet nuget push *.nupkg -k ${GITHUB_TOKEN} -s "Github"  --skip-duplicate --no-symbols
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          NUGET_USERNAME: ${{ secrets.GITHUB_REPOSITORY_OWNER }}
          NUGET_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
