name: Build, Test, and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # Modifier selon votre version du SDK
          
      - name: Configurer la source NuGet GitHub Packages
        run: dotnet nuget add source --username $GITHUB_REPOSITORY_OWNER --password ${{ secrets.GITHUB_TOKEN }} --name github "https://nuget.pkg.github.com/$GITHUB_REPOSITORY_OWNER/index.json"

      - name: Restore dependencies
        run: dotnet restore src/BitCrafts.Module.Users.sln

      - name: Build project
        run: dotnet build src/BitCrafts.Module.Users.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test src/BitCrafts.Module.Users.sln --no-restore --verbosity normal

      - name: Pack NuGet package
        run: dotnet pack src/BitCrafts.Module.Users.sln --configuration Release --no-restore --output .

      - name: Publish NuGet package to GitHub Packages
        run: dotnet nuget push *.nupkg --source "github"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
