name: Build, Test, and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Remplacer les variables dans NuGet.config
        run: |
           sed -i "s|{NUGET_USERNAME}|${GITHUB_REPOSITORY_OWNER}|g" nuget.config
           sed -i "s|{NUGET_PASSWORD}|${{ secrets.GITHUB_TOKEN }}|g" nuget.config
      
      - name: Restore dependencies
        run: dotnet restore BitCrafts.Module.Users.sln

      - name: Build Module
        run: dotnet build src/BitCrafts.Module.Users/BitCrafts.Module.Users.csproj --configuration Release --no-restore

      - name: Pack NuGet package 1
        run: dotnet pack src/BitCrafts.Module.Users/BitCrafts.Module.Users.csproj --configuration Release --no-restore --output .
        
      - name: Pack NuGet package 2
        run: dotnet pack src/BitCrafts.Module.Users.Abstraction/BitCrafts.Module.Users.Abstraction.csproj --configuration Release --no-restore --output .

      - name: Publish NuGet package to GitHub Packages
        run: dotnet nuget push *.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/${GITHUB_REPOSITORY_OWNER}/index.json  --skip-duplicate --no-symbols
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          
